### ISSUE TITLE
mod is causing game settings to revert to default

### ISSUE THREAD

**Issue by qualiall** [rcav8tr/CS2Mod-ImprovedPieCharts#1]
Hello,

When I installed this mod, it caused all game settings (sound, graphics, interface and so on) to revert back to default settings.  I reset my settings how I like it and relaunched-the settings were reset again.  I set things back, closed the game, uninstalled ImprovedPieCharts, and the problem was resolved.

**Comment by rcav8tr** [comment]
The game has done that to me multiple times, even before I started creating this mod.  It is not this mod.  It is something in the game.  It happened to me often enough that I even created a backup copy of the game's settings file so when it happens, I can simply restore the backup file.  The game's settings file is located at:
C:\Users\<name>\AppData\LocalLow\Colossal Order\Cities Skylines II\Settings.coc
Don't keep the backup file in the same folder or the game will delete it.  Keep the backup file in a different folder.
